import { EventMapping } from './mappings.model';

// Every Event tag in the archive, mapped to a tournament name, its section, where it
// was played and, where the round was written into the event name, the round
export const EVENT_MAPPINGS: Record<string, EventMapping> = {
  '2005 London CC Ch.': { tournament: 'Club Championship', location: 'London' },
  '2017 London Ch Match': {
    tournament: 'Club Championship',
    section: 'Match',
    location: 'London',
  },
  '2017 London Ch Phase 1': {
    tournament: 'Club Championship',
    section: 'Phase 1',
    location: 'London',
  },
  '2017 London Ch Phase 2': {
    tournament: 'Club Championship',
    section: 'Phase 2',
    location: 'London',
  },
  '2017 London Ch playoff': {
    tournament: 'Club Championship',
    section: 'Playoff',
    location: 'London',
  },
  '2017 London Ch-B Match': {
    tournament: 'Club Championship',
    section: 'B Match',
    location: 'London',
  },
  '2017 London Ch-B Phase 2': {
    tournament: 'Club Championship',
    section: 'B Phase 2',
    location: 'London',
  },
  '2017 London Ch-C Phase 2': {
    tournament: 'Club Championship',
    section: 'C Phase 2',
    location: 'London',
  },
  '2017 Winter Active': { tournament: 'Winter Active', location: 'London' },
  '2018 London Ch Match': {
    tournament: 'Club Championship',
    section: 'Match',
    location: 'London',
  },
  '2018 London Ch Phase 1': {
    tournament: 'Club Championship',
    section: 'Phase 1',
    location: 'London',
  },
  '2018 London Ch Phase 2': {
    tournament: 'Club Championship',
    section: 'Phase 2',
    location: 'London',
  },
  '2018 London Ch-B Match': {
    tournament: 'Club Championship',
    section: 'B Match',
    location: 'London',
  },
  '2018 London Ch-B Phase 2': {
    tournament: 'Club Championship',
    section: 'B Phase 2',
    location: 'London',
  },
  '2018 London Ch-C Phase 2': {
    tournament: 'Club Championship',
    section: 'C Phase 2',
    location: 'London',
  },
  '2018 Stratford Ch': { tournament: 'Stratford Championship', location: 'Stratford' },
  '2019 Active Ch': { tournament: 'Active Championship', location: 'London' },
  '2019 London Ch-A Match': {
    tournament: 'Club Championship',
    section: 'A Match',
    location: 'London',
  },
  '2019 London Ch-B Match': {
    tournament: 'Club Championship',
    section: 'B Match',
    location: 'London',
  },
  '2019 London-Ch A': {
    tournament: 'Club Championship',
    section: 'A',
    location: 'London',
  },
  '2019 London-Ch B': {
    tournament: 'Club Championship',
    section: 'B',
    location: 'London',
  },
  '2019 London-Ch C': {
    tournament: 'Club Championship',
    section: 'C',
    location: 'London',
  },
  '2019 London-Ch D': {
    tournament: 'Club Championship',
    section: 'D',
    location: 'London',
  },
  '2019 London-Ch Qualifier': {
    tournament: 'Club Championship',
    section: 'Qualifier',
    location: 'London',
  },
  '2019 Teams - Board 1': {
    tournament: 'Team Tournament',
    section: 'Board 1',
    location: 'London',
  },
  '2019 Teams - Board 2': {
    tournament: 'Team Tournament',
    section: 'Board 2',
    location: 'London',
  },
  '2019 Teams - Board 3': {
    tournament: 'Team Tournament',
    section: 'Board 3',
    location: 'London',
  },
  '2019 Teams - Board 4': {
    tournament: 'Team Tournament',
    section: 'Board 4',
    location: 'London',
  },
  '2019 Teams - Board 5': {
    tournament: 'Team Tournament',
    section: 'Board 5',
    location: 'London',
  },
  '2019 Teams - Board 6': {
    tournament: 'Team Tournament',
    section: 'Board 6',
    location: 'London',
  },
  '2019 Teams - Board 7': {
    tournament: 'Team Tournament',
    section: 'Board 7',
    location: 'London',
  },
  '2019 Teams - Board 8': {
    tournament: 'Team Tournament',
    section: 'Board 8',
    location: 'London',
  },
  '2019 Teams - Board 9': {
    tournament: 'Team Tournament',
    section: 'Board 9',
    location: 'London',
  },
  '2022 London Ch A1': {
    tournament: 'Club Championship',
    section: 'A1',
    location: 'London',
  },
  '2022 London Ch A2': {
    tournament: 'Club Championship',
    section: 'A2',
    location: 'London',
  },
  '2022 London Ch B1': {
    tournament: 'Club Championship',
    section: 'B1',
    location: 'London',
  },
  '2022 London Ch B2': {
    tournament: 'Club Championship',
    section: 'B2',
    location: 'London',
  },
  '2022 London Ch C': {
    tournament: 'Club Championship',
    section: 'C',
    location: 'London',
  },
  '2022 London Ch C1': {
    tournament: 'Club Championship',
    section: 'C1',
    location: 'London',
  },
  '2022 London Ch C2': {
    tournament: 'Club Championship',
    section: 'C2',
    location: 'London',
  },
  '2022 London Ch MATCH': {
    tournament: 'Club Championship',
    section: 'Match',
    location: 'London',
  },
  '2023 London Ch A Match': {
    tournament: 'Club Championship',
    section: 'A Match',
    location: 'London',
  },
  '2023 London Ch A1': {
    tournament: 'Club Championship',
    section: 'A1',
    location: 'London',
  },
  '2023 London Ch A2': {
    tournament: 'Club Championship',
    section: 'A2',
    location: 'London',
  },
  '2023 London Ch B Match': {
    tournament: 'Club Championship',
    section: 'B Match',
    location: 'London',
  },
  '2023 London Ch B Match Playoff': {
    tournament: 'Club Championship',
    section: 'B Match Playoff',
    location: 'London',
  },
  '2023 London Ch B1': {
    tournament: 'Club Championship',
    section: 'B1',
    location: 'London',
  },
  '2023 London Ch B2': {
    tournament: 'Club Championship',
    section: 'B2',
    location: 'London',
  },
  '2023 London Ch C Match': {
    tournament: 'Club Championship',
    section: 'C Match',
    location: 'London',
  },
  '2023 London Ch C1': {
    tournament: 'Club Championship',
    section: 'C1',
    location: 'London',
  },
  '2023 London Ch C2': {
    tournament: 'Club Championship',
    section: 'C2',
    location: 'London',
  },
  '2023 London Ch D Match': {
    tournament: 'Club Championship',
    section: 'D Match',
    location: 'London',
  },
  '2023 London Ch D1': {
    tournament: 'Club Championship',
    section: 'D1',
    location: 'London',
  },
  '2023 London Ch D2': {
    tournament: 'Club Championship',
    section: 'D2',
    location: 'London',
  },
  '2024 London Ch A Match': {
    tournament: 'Club Championship',
    section: 'A Match',
    location: 'London',
  },
  '2024 London Ch A Match Pl-Off': {
    tournament: 'Club Championship',
    section: 'A Match Playoff',
    location: 'London',
  },
  '2024 London Ch A1': {
    tournament: 'Club Championship',
    section: 'A1',
    location: 'London',
  },
  '2024 London Ch A2': {
    tournament: 'Club Championship',
    section: 'A2',
    location: 'London',
  },
  '2024 London Ch B Match': {
    tournament: 'Club Championship',
    section: 'B Match',
    location: 'London',
  },
  '2024 London Ch B Match Pl-Off': {
    tournament: 'Club Championship',
    section: 'B Match Playoff',
    location: 'London',
  },
  '2024 London Ch B1': {
    tournament: 'Club Championship',
    section: 'B1',
    location: 'London',
  },
  '2024 London Ch B2': {
    tournament: 'Club Championship',
    section: 'B2',
    location: 'London',
  },
  '2024 London Ch C Match': {
    tournament: 'Club Championship',
    section: 'C Match',
    location: 'London',
  },
  '2024 London Ch C Match Pl-Off': {
    tournament: 'Club Championship',
    section: 'C Match Playoff',
    location: 'London',
  },
  '2024 London Ch C1': {
    tournament: 'Club Championship',
    section: 'C1',
    location: 'London',
  },
  '2024 London Ch C2': {
    tournament: 'Club Championship',
    section: 'C2',
    location: 'London',
  },
  '2024 London Ch D': {
    tournament: 'Club Championship',
    section: 'D',
    location: 'London',
  },
  '2024 London Ch E': {
    tournament: 'Club Championship',
    section: 'E',
    location: 'London',
  },
  '2025 London Ch A MATCH': {
    tournament: 'Club Championship',
    section: 'A Match',
    location: 'London',
  },
  '2025 London Ch A1': {
    tournament: 'Club Championship',
    section: 'A1',
    location: 'London',
  },
  '2025 London Ch A1 playoff rd1': {
    tournament: 'Club Championship',
    section: 'A1 Playoff',
    location: 'London',
    round: '1',
  },
  '2025 London Ch A1 playoff rd2': {
    tournament: 'Club Championship',
    section: 'A1 Playoff',
    location: 'London',
    round: '2',
  },
  '2025 London Ch A1 playoff rd3': {
    tournament: 'Club Championship',
    section: 'A1 Playoff',
    location: 'London',
    round: '3',
  },
  '2025 London Ch A1 playoff rd4': {
    tournament: 'Club Championship',
    section: 'A1 Playoff',
    location: 'London',
    round: '4',
  },
  '2025 London Ch A1 playoff rd5': {
    tournament: 'Club Championship',
    section: 'A1 Playoff',
    location: 'London',
    round: '5',
  },
  '2025 London Ch A1 playoff rd6': {
    tournament: 'Club Championship',
    section: 'A1 Playoff',
    location: 'London',
    round: '6',
  },
  '2025 London Ch A2': {
    tournament: 'Club Championship',
    section: 'A2',
    location: 'London',
  },
  '2025 London Ch B MATCH': {
    tournament: 'Club Championship',
    section: 'B Match',
    location: 'London',
  },
  '2025 London Ch B1': {
    tournament: 'Club Championship',
    section: 'B1',
    location: 'London',
  },
  '2025 London Ch B2': {
    tournament: 'Club Championship',
    section: 'B2',
    location: 'London',
  },
  '2025 London Ch C MATCH': {
    tournament: 'Club Championship',
    section: 'C Match',
    location: 'London',
  },
  '2025 London Ch C MATCH playoff': {
    tournament: 'Club Championship',
    section: 'C Match Playoff',
    location: 'London',
  },
  '2025 London Ch C1': {
    tournament: 'Club Championship',
    section: 'C1',
    location: 'London',
  },
  '2025 London Ch C2': {
    tournament: 'Club Championship',
    section: 'C2',
    location: 'London',
  },
  '2025 London Ch D MATCH': {
    tournament: 'Club Championship',
    section: 'D Match',
    location: 'London',
  },
  '2025 London Ch D1': {
    tournament: 'Club Championship',
    section: 'D1',
    location: 'London',
  },
  '2025 London Ch D2': {
    tournament: 'Club Championship',
    section: 'D2',
    location: 'London',
  },
  '2025 London Ch E': {
    tournament: 'Club Championship',
    section: 'E',
    location: 'London',
  },
  '2025 London Ch F': {
    tournament: 'Club Championship',
    section: 'F',
    location: 'London',
  },
  '2025 London Ch G': {
    tournament: 'Club Championship',
    section: 'G',
    location: 'London',
  },
  '2025 London Ch YA': {
    tournament: 'Club Championship',
    section: 'YA',
    location: 'London',
  },
  'Adelaide (Wch jr)': { tournament: 'World Junior Championship', location: 'Adelaide' },
  'Adelaide (Wch-jr)': { tournament: 'World Junior Championship', location: 'Adelaide' },
  'Biel - Open': { tournament: 'Open', location: 'Biel' },
  'Brantford, Canada Friendship League Apr': {
    tournament: 'Friendship League April',
    location: 'Brantford',
  },
  Canada: { tournament: 'Canada' },
  'Canadian Open': { tournament: 'Canadian Open' },
  'Chicago (U.S. Open)': { tournament: 'US Open', location: 'Chicago' },
  'Chicago - US Open': { tournament: 'US Open', location: 'Chicago' },
  'Debrecen - Open': { tournament: 'Open', location: 'Debrecen' },
  'Edmonton (CAN-ch jr)': {
    tournament: 'Canadian Junior Championship',
    location: 'Edmonton',
  },
  'Edmonton - (CAN-ch jr)': {
    tournament: 'Canadian Junior Championship',
    location: 'Edmonton',
  },
  'Fanshawe College (Active)': {
    tournament: 'Fanshawe College Active',
    location: 'London',
  },
  'Guelph, Canada (Ontario op)': { tournament: 'Ontario Open', location: 'Guelph' },
  'Kingston, Ontario - Toronto/Montreal': {
    tournament: 'Toronto/Montreal',
    location: 'Kingston',
  },
  'Kitchener, Canada (K-W Fall Open)': {
    tournament: 'K-W Fall Open',
    location: 'Kitchener',
  },
  'Kitchener-Waterloo - Fall Open': {
    tournament: 'K-W Fall Open',
    location: 'Kitchener',
  },
  'London - Lloyds Bank': { tournament: 'Lloyds Bank', location: 'London' },
  'London vs. Windsor, Canada - II (tt)': {
    tournament: 'London vs. Windsor, Canada - II (tt)',
  },
  'London, Canada': { tournament: '', location: 'London' },
  'London, Canada  (Ontario Jr ch)': {
    tournament: 'Ontario Junior Championship',
    location: 'London',
  },
  'London, Canada (Active Ch)': { tournament: 'Active Championship', location: 'London' },
  'London, Canada (Active Championship)': {
    tournament: 'Active Championship',
    location: 'London',
  },
  'London, Canada (Active Champoionship)': {
    tournament: 'Active Championship',
    location: 'London',
  },
  'London, Canada (Active Cmpship)': {
    tournament: 'Active Championship',
    location: 'London',
  },
  'London, Canada (Apr. 16)': { tournament: 'April 16', location: 'London' },
  'London, Canada (Apr. 23)': { tournament: 'April 23', location: 'London' },
  'London, Canada (Apr. 4)': { tournament: 'April 4', location: 'London' },
  'London, Canada (Apr. Mini-Active)': {
    tournament: 'April Mini Active',
    location: 'London',
  },
  'London, Canada (apr. Mini-Active)': {
    tournament: 'April Mini Active',
    location: 'London',
  },
  'London, Canada (April Open)': { tournament: 'April Open', location: 'London' },
  'London, Canada (August 4 in 1)': { tournament: 'August 4 in 1', location: 'London' },
  'London, Canada (August Active)': { tournament: 'August Active', location: 'London' },
  'London, Canada (ch B)': {
    tournament: 'Club Championship',
    section: 'B',
    location: 'London',
  },
  'London, Canada (ch plof)': {
    tournament: 'Club Championship',
    section: 'Playoff',
    location: 'London',
  },
  'London, Canada (ch)': { tournament: 'Club Championship', location: 'London' },
  'London, Canada (Ch-A)': {
    tournament: 'Club Championship',
    section: 'A',
    location: 'London',
  },
  'London, Canada (Ch-B)': {
    tournament: 'Club Championship',
    section: 'B',
    location: 'London',
  },
  'London, Canada (ch-B)': {
    tournament: 'Club Championship',
    section: 'B',
    location: 'London',
  },
  'London, Canada (Ch-C)': {
    tournament: 'Club Championship',
    section: 'C',
    location: 'London',
  },
  'London, Canada (ch-C)': {
    tournament: 'Club Championship',
    section: 'C',
    location: 'London',
  },
  'London, Canada (Ch-D)': {
    tournament: 'Club Championship',
    section: 'D',
    location: 'London',
  },
  'London, Canada (ch-D)': {
    tournament: 'Club Championship',
    section: 'D',
    location: 'London',
  },
  'London, Canada (ch-D1)': {
    tournament: 'Club Championship',
    section: 'D1',
    location: 'London',
  },
  'London, Canada (Ch-E)': {
    tournament: 'Club Championship',
    section: 'E',
    location: 'London',
  },
  'London, Canada (ch-E)': {
    tournament: 'Club Championship',
    section: 'E',
    location: 'London',
  },
  'London, Canada (Ch-F)': {
    tournament: 'Club Championship',
    section: 'F',
    location: 'London',
  },
  'London, Canada (ch-F)': {
    tournament: 'Club Championship',
    section: 'F',
    location: 'London',
  },
  'London, Canada (ch-G)': {
    tournament: 'Club Championship',
    section: 'G',
    location: 'London',
  },
  'London, Canada (Dec. Active)': { tournament: 'December Active', location: 'London' },
  'London, Canada (Emanuel Lasker Memorial': {
    tournament: 'Emanuel Lasker Memorial',
    location: 'London',
  },
  'London, Canada (Fall Brawl)': { tournament: 'Fall Brawl', location: 'London' },
  'London, Canada (Fall Classic RD )': { tournament: 'Fall Classic', location: 'London' },
  'London, Canada (Fall Classic RD1)': {
    tournament: 'Fall Classic',
    location: 'London',
    round: '1',
  },
  'London, Canada (Fall Classic RD2)': {
    tournament: 'Fall Classic',
    location: 'London',
    round: '2',
  },
  'London, Canada (Fall Classic RD3)': {
    tournament: 'Fall Classic',
    location: 'London',
    round: '3',
  },
  'London, Canada (Fall Classic RD4)': {
    tournament: 'Fall Classic',
    location: 'London',
    round: '4',
  },
  'London, Canada (Fall Classic RD5)': {
    tournament: 'Fall Classic',
    location: 'London',
    round: '5',
  },
  'London, Canada (Fall Classic)': { tournament: 'Fall Classic', location: 'London' },
  'London, Canada (Fall Open)': { tournament: 'Fall Open', location: 'London' },
  'London, Canada (Fall Swiss RD1)': {
    tournament: 'Fall Swiss',
    location: 'London',
    round: '1',
  },
  'London, Canada (Fall Swiss RD2)': {
    tournament: 'Fall Swiss',
    location: 'London',
    round: '2',
  },
  'London, Canada (Fall Swiss RD3)': {
    tournament: 'Fall Swiss',
    location: 'London',
    round: '3',
  },
  'London, Canada (Fall Swiss RD4)': {
    tournament: 'Fall Swiss',
    location: 'London',
    round: '4',
  },
  'London, Canada (Fall Swiss RD5)': {
    tournament: 'Fall Swiss',
    location: 'London',
    round: '5',
  },
  'London, Canada (Fall Swiss RD6)': {
    tournament: 'Fall Swiss',
    location: 'London',
    round: '6',
  },
  'London, Canada (Fall Swiss)': { tournament: 'Fall Swiss', location: 'London' },
  'London, Canada (Feb. 10)': { tournament: 'February 10', location: 'London' },
  'London, Canada (Feb.Mini-Active)': {
    tournament: 'February Mini Active',
    location: 'London',
  },
  'London, Canada (February 10)': { tournament: 'February 10', location: 'London' },
  'London, Canada (February 4 In 1)': {
    tournament: 'February 4 in 1',
    location: 'London',
  },
  'London, Canada (February 4 in 1)': {
    tournament: 'February 4 in 1',
    location: 'London',
  },
  'London, Canada (February Swiss)': { tournament: 'February Swiss', location: 'London' },
  'London, Canada (Geza Fuster - A)': {
    tournament: 'Geza Fuster Memorial',
    section: 'A',
    location: 'London',
  },
  'London, Canada (Geza Fuster - B)': {
    tournament: 'Geza Fuster Memorial',
    section: 'B',
    location: 'London',
  },
  'London, Canada (Geza Fuster - C)': {
    tournament: 'Geza Fuster Memorial',
    section: 'C',
    location: 'London',
  },
  'London, Canada (Geza Fuster - D)': {
    tournament: 'Geza Fuster Memorial',
    section: 'D',
    location: 'London',
  },
  'London, Canada (Geza Fuster - E)': {
    tournament: 'Geza Fuster Memorial',
    section: 'E',
    location: 'London',
  },
  'London, Canada (Geza Fuster -A)': {
    tournament: 'Geza Fuster Memorial',
    section: 'A',
    location: 'London',
  },
  'London, Canada (Geza Fuster -B)': {
    tournament: 'Geza Fuster Memorial',
    section: 'B',
    location: 'London',
  },
  'London, Canada (Geza Fuster -C)': {
    tournament: 'Geza Fuster Memorial',
    section: 'C',
    location: 'London',
  },
  'London, Canada (Geza Fuster A)': {
    tournament: 'Geza Fuster Memorial',
    section: 'A',
    location: 'London',
  },
  'London, Canada (Geza Fuster A2)': {
    tournament: 'Geza Fuster Memorial',
    section: 'A2',
    location: 'London',
  },
  'London, Canada (Geza Fuster B)': {
    tournament: 'Geza Fuster Memorial',
    section: 'B',
    location: 'London',
  },
  'London, Canada (Geza Fuster B2)': {
    tournament: 'Geza Fuster Memorial',
    section: 'B2',
    location: 'London',
  },
  'London, Canada (Geza Fuster C)': {
    tournament: 'Geza Fuster Memorial',
    section: 'C',
    location: 'London',
  },
  'London, Canada (Geza Fuster C2)': {
    tournament: 'Geza Fuster Memorial',
    section: 'C2',
    location: 'London',
  },
  'London, Canada (Geza Fuster D)': {
    tournament: 'Geza Fuster Memorial',
    section: 'D',
    location: 'London',
  },
  'London, Canada (Geza Fuster D2)': {
    tournament: 'Geza Fuster Memorial',
    section: 'D2',
    location: 'London',
  },
  'London, Canada (Geza Fuster E)': {
    tournament: 'Geza Fuster Memorial',
    section: 'E',
    location: 'London',
  },
  'London, Canada (Geza Fuster E1)': {
    tournament: 'Geza Fuster Memorial',
    section: 'E1',
    location: 'London',
  },
  'London, Canada (Geza Fuster E2)': {
    tournament: 'Geza Fuster Memorial',
    section: 'E2',
    location: 'London',
  },
  'London, Canada (Geza Fuster Mem.)': {
    tournament: 'Geza Fuster Memorial',
    location: 'London',
  },
  'London, Canada (Geza Fuster Memorial -': {
    tournament: 'Geza Fuster Memorial',
    location: 'London',
  },
  'London, Canada (Geza Fuster Memorial)': {
    tournament: 'Geza Fuster Memorial',
    location: 'London',
  },
  'London, Canada (Geza Fuster memorial)': {
    tournament: 'Geza Fuster Memorial',
    location: 'London',
  },
  'London, Canada (Geza Fuster Memorial-B)': {
    tournament: 'Geza Fuster Memorial',
    section: 'B',
    location: 'London',
  },
  'London, Canada (Geza Fuster Memorial-C)': {
    tournament: 'Geza Fuster Memorial',
    section: 'C',
    location: 'London',
  },
  'London, Canada (Geza Fuster Memorial-D)': {
    tournament: 'Geza Fuster Memorial',
    section: 'D',
    location: 'London',
  },
  'London, Canada (Geza Fuster)': {
    tournament: 'Geza Fuster Memorial',
    location: 'London',
  },
  'London, Canada (Grand Opening)': { tournament: 'Grand Opening', location: 'London' },
  'London, Canada (Grand Prix)': { tournament: 'Grand Prix', location: 'London' },
  'London, Canada (Jan.Mini-Active)': {
    tournament: 'January Mini Active',
    location: 'London',
  },
  'London, Canada (Jr.Cmp.Qual.)': {
    tournament: 'Junior Championship',
    section: 'Qualifier',
    location: 'London',
  },
  'London, Canada (Jr.Fall Brawl-A)': {
    tournament: 'Junior Fall Brawl',
    section: 'A',
    location: 'London',
  },
  'London, Canada (Jr.Fall Brawl-B)': {
    tournament: 'Junior Fall Brawl',
    section: 'B',
    location: 'London',
  },
  'London, Canada (Jr.May Active)': {
    tournament: 'Junior May Active',
    location: 'London',
  },
  'London, Canada (Jr.Spring Active)': {
    tournament: 'Junior Spring Active',
    location: 'London',
  },
  'London, Canada (June 2)': { tournament: 'June 2', location: 'London' },
  'London, Canada (June Active-A)': {
    tournament: 'June Active',
    section: 'A',
    location: 'London',
  },
  'London, Canada (June Active-B)': {
    tournament: 'June Active',
    section: 'B',
    location: 'London',
  },
  'London, Canada (June Mini-Active)': {
    tournament: 'June Mini Active',
    location: 'London',
  },
  'London, Canada (Jung Blindfold Simul)': {
    tournament: 'Jung Blindfold Simul',
    location: 'London',
  },
  'London, Canada (Jung blindfold)': {
    tournament: 'Jung Blindfold Simul',
    location: 'London',
  },
  'London, Canada (Ldn Jr.Cmpship)': {
    tournament: 'Junior Championship',
    location: 'London',
  },
  'London, Canada (Ldn SWOCL)': { tournament: 'Ldn SWOCL', location: 'London' },
  'London, Canada (m)': { tournament: 'm', location: 'London' },
  'London, Canada (m1)': { tournament: 'm1', location: 'London' },
  'London, Canada (m2)': { tournament: 'm2', location: 'London' },
  'London, Canada (m3)': { tournament: 'm3', location: 'London' },
  'London, Canada (m4)': { tournament: 'm4', location: 'London' },
  'London, Canada (Mar. 14)': { tournament: 'March 14', location: 'London' },
  'London, Canada (Mar. 18)': { tournament: 'March 18', location: 'London' },
  'London, Canada (Mar. 21)': { tournament: 'March 21', location: 'London' },
  'London, Canada (Mar. 3)': { tournament: 'March 3', location: 'London' },
  'London, Canada (March 4 in 1 op)': {
    tournament: 'March 4 in 1 Open',
    location: 'London',
  },
  'London, Canada (March Mini-Active)': {
    tournament: 'March Mini Active',
    location: 'London',
  },
  'London, Canada (March Mini-Active)(not': {
    tournament: 'March Mini Active',
    location: 'London',
  },
  'London, Canada (May 14)': { tournament: 'May 14', location: 'London' },
  'London, Canada (May 30)': { tournament: 'May 30', location: 'London' },
  'London, Canada (May 7)': { tournament: 'May 7', location: 'London' },
  'London, Canada (May Active)': { tournament: 'May Active', location: 'London' },
  'London, Canada (May Open)': { tournament: 'May Open', location: 'London' },
  'London, Canada (Nov. Mini Active)': {
    tournament: 'November Mini Active',
    location: 'London',
  },
  'London, Canada (Nov. Mini-Active)': {
    tournament: 'November Mini Active',
    location: 'London',
  },
  'London, Canada (November 4 in 1)': {
    tournament: 'November 4 in 1',
    location: 'London',
  },
  'London, Canada (November Mini Active)': {
    tournament: 'November Mini Active',
    location: 'London',
  },
  'London, Canada (Oct. Mini-Active)': {
    tournament: 'October Mini Active',
    location: 'London',
  },
  'London, Canada (October 4 in 1)': { tournament: 'October 4 in 1', location: 'London' },
  'London, Canada (October Mini Active)': {
    tournament: 'October Mini Active',
    location: 'London',
  },
  'London, Canada (op)': { tournament: 'Open', location: 'London' },
  'London, Canada (Quicky 01)': { tournament: 'Quicky 01', location: 'London' },
  'London, Canada (Quicky 02)': { tournament: 'Quicky 02', location: 'London' },
  'London, Canada (Quicky 03)': { tournament: 'Quicky 03', location: 'London' },
  'London, Canada (Quicky 04)': { tournament: 'Quicky 04', location: 'London' },
  'London, Canada (Quicky 05)': { tournament: 'Quicky 05', location: 'London' },
  'London, Canada (Quicky 06)': { tournament: 'Quicky 06', location: 'London' },
  'London, Canada (Quicky 07)': { tournament: 'Quicky 07', location: 'London' },
  'London, Canada (Quicky 08)': { tournament: 'Quicky 08', location: 'London' },
  'London, Canada (Quicky 09)': { tournament: 'Quicky 09', location: 'London' },
  'London, Canada (Quicky 10)': { tournament: 'Quicky 10', location: 'London' },
  'London, Canada (Quicky 11)': { tournament: 'Quicky 11', location: 'London' },
  'London, Canada (Quicky 12)': { tournament: 'Quicky 12', location: 'London' },
  'London, Canada (Quicky 13)': { tournament: 'Quicky 13', location: 'London' },
  'London, Canada (Quicky 14)': { tournament: 'Quicky 14', location: 'London' },
  'London, Canada (Quicky 15)': { tournament: 'Quicky 15', location: 'London' },
  'London, Canada (Quicky 16)': { tournament: 'Quicky 16', location: 'London' },
  'London, Canada (Quicky 17)': { tournament: 'Quicky 17', location: 'London' },
  'London, Canada (Scholastic)': { tournament: 'Scholastic', location: 'London' },
  'London, Canada (Sept Open)': { tournament: 'September Open', location: 'London' },
  'London, Canada (Sept. Mini-Active)': {
    tournament: 'September Mini Active',
    location: 'London',
  },
  'London, Canada (Sept.Jr.Active)': {
    tournament: 'September Junior Active',
    location: 'London',
  },
  'London, Canada (September 4 in 1)': {
    tournament: 'September 4 in 1',
    location: 'London',
  },
  'London, Canada (September Mini Active)': {
    tournament: 'September Mini Active',
    location: 'London',
  },
  'London, Canada (September Swiss)': {
    tournament: 'September Swiss',
    location: 'London',
  },
  'London, Canada (Simul - White Oaks Mall': {
    tournament: 'Simul - White Oaks Mall',
    location: 'London',
  },
  'London, Canada (Simul)': { tournament: 'Simul', location: 'London' },
  'London, Canada (skittles)': { tournament: 'Skittles', location: 'London' },
  'London, Canada (Spring Active': { tournament: 'Spring Active', location: 'London' },
  'London, Canada (Spring Active)': { tournament: 'Spring Active', location: 'London' },
  'London, Canada (Spring Op)': { tournament: 'Spring Open', location: 'London' },
  'London, Canada (Spring Open - Reserve)': {
    tournament: 'Spring Open Reserve',
    location: 'London',
  },
  'London, Canada (Spring Open)': { tournament: 'Spring Open', location: 'London' },
  'London, Canada (Summer Accomodation)': {
    tournament: 'Summer Accomodation',
    location: 'London',
  },
  'London, Canada (Summer End Open)': {
    tournament: 'Summer End Open',
    location: 'London',
  },
  'London, Canada (Summer Sizzler)': { tournament: 'Summer Sizzler', location: 'London' },
  'London, Canada (T.Southam Mem)': {
    tournament: 'Tom Southam Memorial',
    location: 'London',
  },
  'London, Canada (The Classic)': { tournament: 'The Classic', location: 'London' },
  'London, Canada (Tolpuddle Op)': { tournament: 'Tolpuddle Open', location: 'London' },
  'London, Canada (Tolpuddle Open)': { tournament: 'Tolpuddle Open', location: 'London' },
  'London, Canada (Tolpuddle Open) (tt)': {
    tournament: 'Tolpuddle Open (tt)',
    location: 'London',
  },
  'London, Canada (Van Weeren)': { tournament: 'Van Weeren', location: 'London' },
  'London, Canada (Winter Classic 04)': {
    tournament: 'Winter Classic',
    location: 'London',
    round: '4',
  },
  'London, Canada (Winter Classic 06)': {
    tournament: 'Winter Classic',
    location: 'London',
    round: '6',
  },
  'London, Canada (Winter Classic 07)': {
    tournament: 'Winter Classic',
    location: 'London',
    round: '7',
  },
  'London, Canada (Winter Classic A)': {
    tournament: 'Winter Classic',
    section: 'A',
    location: 'London',
  },
  'London, Canada (Winter Classic B)': {
    tournament: 'Winter Classic',
    section: 'B',
    location: 'London',
  },
  'London, Canada (Winter Classic C)': {
    tournament: 'Winter Classic',
    section: 'C',
    location: 'London',
  },
  'London, Canada (Winter Classic D)': {
    tournament: 'Winter Classic',
    section: 'D',
    location: 'London',
  },
  'London, Canada (Winter Classic)': { tournament: 'Winter Classic', location: 'London' },
  'London, Canada (Xmas Active)': { tournament: 'Xmas Active', location: 'London' },
  'London, Canada - (ch B)': {
    tournament: 'Club Championship',
    section: 'B',
    location: 'London',
  },
  'London, Canada - (ch C)': {
    tournament: 'Club Championship',
    section: 'C',
    location: 'London',
  },
  'London, Canada - (ch)': { tournament: 'Club Championship', location: 'London' },
  'London, Canada - (ch-B)': {
    tournament: 'Club Championship',
    section: 'B',
    location: 'London',
  },
  'London, Canada - (ch-C)': {
    tournament: 'Club Championship',
    section: 'C',
    location: 'London',
  },
  'London, Canada - (m/1)': { tournament: 'm/1', location: 'London' },
  'London, Canada - (m/2)': { tournament: 'm/2', location: 'London' },
  'London, Canada - (m/3)': { tournament: 'm/3', location: 'London' },
  'London, Canada - (m/4)': { tournament: 'm/4', location: 'London' },
  'London, Canada - (m/6)': { tournament: 'm/6', location: 'London' },
  'London, Canada - 2nd Aug Jr.': { tournament: '2nd August Junior', location: 'London' },
  'London, Canada - Active (m)': { tournament: 'Active (m)', location: 'London' },
  'London, Canada - Active Championship': {
    tournament: 'Active Championship',
    location: 'London',
  },
  'London, Canada - Active Pickup': { tournament: 'Active Pickup', location: 'London' },
  'London, Canada - Active Playoff': { tournament: 'Active Playoff', location: 'London' },
  'London, Canada - April Junior': { tournament: 'April Junior', location: 'London' },
  'London, Canada - August Beginners': {
    tournament: 'August Beginners',
    location: 'London',
  },
  'London, Canada - August Junior': { tournament: 'August Junior', location: 'London' },
  'London, Canada - Beginners Active': {
    tournament: 'Beginners Active',
    location: 'London',
  },
  'London, Canada - Blizzard Open': {
    tournament: 'Winter Blizzard',
    section: 'Open',
    location: 'London',
  },
  'London, Canada - Blizzard U1700': {
    tournament: 'Winter Blizzard',
    section: 'U1700',
    location: 'London',
  },
  'London, Canada - Canada Day Active': {
    tournament: 'Canada Day Active',
    location: 'London',
  },
  'London, Canada - Dec. Junior': { tournament: 'December Junior', location: 'London' },
  'London, Canada - December Junior': {
    tournament: 'December Junior',
    location: 'London',
  },
  'London, Canada - Fall Active': { tournament: 'Fall Active', location: 'London' },
  'London, Canada - Fall Harvest': { tournament: 'Fall Harvest', location: 'London' },
  'London, Canada - Fall Harvest Open': {
    tournament: 'Fall Harvest',
    section: 'Open',
    location: 'London',
  },
  'London, Canada - Fall Harvest U1700': {
    tournament: 'Fall Harvest',
    section: 'U1700',
    location: 'London',
  },
  'London, Canada - Fall Open': { tournament: 'Fall Open', location: 'London' },
  'London, Canada - Fall U1600': {
    tournament: 'Fall Open',
    section: 'U1600',
    location: 'London',
  },
  'London, Canada - Fall U1800': {
    tournament: 'Fall Open',
    section: 'U1800',
    location: 'London',
  },
  'London, Canada - Feb. Active': { tournament: 'February Active', location: 'London' },
  'London, Canada - February Junior': {
    tournament: 'February Junior',
    location: 'London',
  },
  'London, Canada - IM Norm Qualifier': {
    tournament: 'IM Norm Qualifier',
    location: 'London',
  },
  'London, Canada - Indian Summer Swiss': {
    tournament: 'Indian Summer Swiss',
    location: 'London',
  },
  'London, Canada - January Junior': { tournament: 'January Junior', location: 'London' },
  'London, Canada - Jr. Crusher': { tournament: 'Junior Crusher', location: 'London' },
  'London, Canada - Jr.Fall Brawl': {
    tournament: 'Junior Fall Brawl',
    location: 'London',
  },
  'London, Canada - Jr.Jan.Active': {
    tournament: 'Junior January Active',
    location: 'London',
  },
  'London, Canada - Jr.Qualifier': {
    tournament: 'Junior Championship',
    section: 'Qualifier',
    location: 'London',
  },
  'London, Canada - July Active': { tournament: 'July Active', location: 'London' },
  'London, Canada - July Double Quad': {
    tournament: 'July Double Quad',
    location: 'London',
  },
  'London, Canada - July Junior': { tournament: 'July Junior', location: 'London' },
  'London, Canada - July Mini Active': {
    tournament: 'July Mini Active',
    location: 'London',
  },
  'London, Canada - June Active': { tournament: 'June Active', location: 'London' },
  'London, Canada - June Beginners': { tournament: 'June Beginners', location: 'London' },
  'London, Canada - June Junior': { tournament: 'June Junior', location: 'London' },
  'London, Canada - Junior Championship': {
    tournament: 'Junior Championship',
    location: 'London',
  },
  'London, Canada - Junior Crusher': { tournament: 'Junior Crusher', location: 'London' },
  'London, Canada - Junior Novice - A': {
    tournament: 'Junior Novice',
    section: 'A',
    location: 'London',
  },
  'London, Canada - Junior Novice - B': {
    tournament: 'Junior Novice',
    section: 'B',
    location: 'London',
  },
  'London, Canada - Junior Novice - C': {
    tournament: 'Junior Novice',
    section: 'C',
    location: 'London',
  },
  'London, Canada - Junior Novice - D': {
    tournament: 'Junior Novice',
    section: 'D',
    location: 'London',
  },
  'London, Canada - Junior Pickup': { tournament: 'Junior Pickup', location: 'London' },
  'London, Canada - Junior Pickup 1': {
    tournament: 'Junior Pickup 1',
    location: 'London',
  },
  'London, Canada - Junior Storm': { tournament: 'Junior Storm', location: 'London' },
  'London, Canada - Junior-Ch': { tournament: 'Junior Championship', location: 'London' },
  'London, Canada - Knockout Matches Rd#1': {
    tournament: 'Knockout Matches',
    location: 'London',
    round: '1',
  },
  'London, Canada - Knockout Matches Rd#2': {
    tournament: 'Knockout Matches',
    location: 'London',
    round: '2',
  },
  'London, Canada - Mar. Active': { tournament: 'March Active', location: 'London' },
  'London, Canada - March Junior': { tournament: 'March Junior', location: 'London' },
  'London, Canada - March Juniors': { tournament: 'March Juniors', location: 'London' },
  'London, Canada - May Junior': { tournament: 'May Junior', location: 'London' },
  'London, Canada - Nov. Quad': { tournament: 'November Quad', location: 'London' },
  'London, Canada - November Junior': {
    tournament: 'November Junior',
    location: 'London',
  },
  'London, Canada - Oct. Active': { tournament: 'October Active', location: 'London' },
  'London, Canada - Oct. Junior': { tournament: 'October Junior', location: 'London' },
  'London, Canada - October Junior': { tournament: 'October Junior', location: 'London' },
  'London, Canada - Open Championship': {
    tournament: 'Open Championship',
    location: 'London',
  },
  'London, Canada - Qualifier A': {
    tournament: 'Club Championship',
    section: 'Qualifier A',
    location: 'London',
  },
  'London, Canada - Qualifier B': {
    tournament: 'Club Championship',
    section: 'Qualifier B',
    location: 'London',
  },
  'London, Canada - Sept Jr Active': {
    tournament: 'September Junior Active',
    location: 'London',
  },
  'London, Canada - Sept. Active': { tournament: 'September Active', location: 'London' },
  'London, Canada - September Active': {
    tournament: 'September Active',
    location: 'London',
  },
  'London, Canada - September Junior': {
    tournament: 'September Junior',
    location: 'London',
  },
  'London, Canada - simul vs. 18 - May, 19': {
    tournament: 'Simul vs. 18 - May, 19',
    location: 'London',
  },
  'London, Canada - Spring Active': { tournament: 'Spring Active', location: 'London' },
  'London, Canada - Spring Swiss': { tournament: 'Spring Swiss', location: 'London' },
  'London, Canada - Spring Thunder': { tournament: 'Spring Thunder', location: 'London' },
  'London, Canada - Summer Sizzler': { tournament: 'Summer Sizzler', location: 'London' },
  'London, Canada - Summer Sizzler Open': {
    tournament: 'Summer Sizzler',
    section: 'Open',
    location: 'London',
  },
  'London, Canada - Summer Sizzler U1700': {
    tournament: 'Summer Sizzler',
    section: 'U1700',
    location: 'London',
  },
  'London, Canada - Summer Swiss': { tournament: 'Summer Swiss', location: 'London' },
  'London, Canada - T.Southam Memorial': {
    tournament: 'Tom Southam Memorial',
    location: 'London',
  },
  'London, Canada - Team Tourney Bd.1': {
    tournament: 'Team Tournament',
    section: 'Board 1',
    location: 'London',
  },
  'London, Canada - Team Tourney Bd.2': {
    tournament: 'Team Tournament',
    section: 'Board 2',
    location: 'London',
  },
  'London, Canada - Team Tourney Bd.3': {
    tournament: 'Team Tournament',
    section: 'Board 3',
    location: 'London',
  },
  'London, Canada - Team Tourney Bd.4': {
    tournament: 'Team Tournament',
    section: 'Board 4',
    location: 'London',
  },
  'London, Canada - Winter Blizzard': {
    tournament: 'Winter Blizzard',
    location: 'London',
  },
  'Luxembourg - Open': { tournament: 'Open', location: 'Luxembourg' },
  'Luxemburg - Open': { tournament: 'Open', location: 'Luxembourg' },
  'Nanaimo, Canada (Vancouver Island Open)': {
    tournament: 'Vancouver Island Open',
    location: 'Nanaimo',
  },
  'New York - Open': { tournament: 'Open', location: 'New York' },
  'North Bay (U-1800)': { tournament: 'Open', section: 'U1800', location: 'North Bay' },
  'North Bay - Open': { tournament: 'Open', location: 'North Bay' },
  'North Bay Open': { tournament: 'Open', location: 'North Bay' },
  'Ontario - Closed (ch)': { tournament: 'Ontario Closed Championship' },
  'Ontario - Open': { tournament: 'Ontario Open' },
  'Ontario Team (ch)': { tournament: 'Ontario Team Championship' },
  'Ottawa - Canadian Open': { tournament: 'Canadian Open', location: 'Ottawa' },
  'Ottawa, Canada - RA Pickup': { tournament: 'RA Pickup', location: 'Ottawa' },
  'Philadelphia - World Open': { tournament: 'World Open', location: 'Philadelphia' },
  'Philidelphia - World Open': { tournament: 'World Open', location: 'Philadelphia' },
  Primorsko: { tournament: '', location: 'Primorsko' },
  'Saint John - Open-2': { tournament: 'Open 2', location: 'Saint John' },
  'Scarborough (active)': { tournament: 'Active', location: 'Scarborough' },
  'Scarborough (CAN-ch)': {
    tournament: 'Canadian Championship',
    location: 'Scarborough',
  },
  'Scarborough, Canada': { tournament: '', location: 'Scarborough' },
  'Scarborough, Canada (December Active)': {
    tournament: 'December Active',
    location: 'Scarborough',
  },
  'Scarborough, Canada (Macedonian Open)': {
    tournament: 'Macedonian Open',
    location: 'Scarborough',
  },
  'Scarborough, Canada (Mar. 23)': { tournament: 'March 23', location: 'Scarborough' },
  'Scarborough, Canada (Mar. 24)': { tournament: 'March 24', location: 'Scarborough' },
  'Scarborough, Canada (Mar. 25)': { tournament: 'March 25', location: 'Scarborough' },
  'Scorborough (CAN-ch)': {
    tournament: 'Canadian Championship',
    location: 'Scarborough',
  },
  Simul: { tournament: 'Simul', location: 'London' },
  skittles: { tournament: 'Skittles' },
  Toronto: { tournament: '', location: 'Toronto' },
  'Toronto  (Simcoe Day)': { tournament: 'Simcoe Day', location: 'Toronto' },
  'Toronto (Canada Day Open)': { tournament: 'Canada Day Open', location: 'Toronto' },
  'Toronto (Canadian Open)': { tournament: 'Canadian Open', location: 'Toronto' },
  'Toronto (CLASSmaster-ch)': {
    tournament: 'Classmaster Championship',
    location: 'Toronto',
  },
  'Toronto (Georgetown Summer Open)': {
    tournament: 'Georgetown Summer Open',
    location: 'Toronto',
  },
  'Toronto (May)': { tournament: 'May', location: 'Toronto' },
  'Toronto (Ontario Op)': { tournament: 'Ontario Open', location: 'Toronto' },
  'Toronto (op)': { tournament: 'Open', location: 'Toronto' },
  'Toronto (Remembrance Day Open)': {
    tournament: 'Remembrance Day Open',
    location: 'Toronto',
  },
  'Toronto (Simcoe op)': { tournament: 'Simcoe Open', location: 'Toronto' },
  'Toronto (Thanksgiving Day Open U2200)': {
    tournament: 'Thanksgiving Open',
    section: 'U2200',
    location: 'Toronto',
  },
  'Toronto -  CLASSmaster (ch)': {
    tournament: 'Classmaster Championship',
    location: 'Toronto',
  },
  'Toronto - Canada Day Open': { tournament: 'Canada Day Open', location: 'Toronto' },
  'Toronto - Canadian Open': { tournament: 'Canadian Open', location: 'Toronto' },
  'Toronto - Casa Loma (rapid)': { tournament: 'Casa Loma Rapid', location: 'Toronto' },
  'Toronto - CLASSmaster (ch)': {
    tournament: 'Classmaster Championship',
    location: 'Toronto',
  },
  'Toronto - Closed (ch)': { tournament: 'Closed Championship', location: 'Toronto' },
  'Toronto - Knights of Spring Open': {
    tournament: 'Knights of Spring Open',
    location: 'Toronto',
  },
  'Toronto - Labor Day Open': { tournament: 'Labour Day Open', location: 'Toronto' },
  'Toronto - Labour Day Open': { tournament: 'Labour Day Open', location: 'Toronto' },
  'Toronto - Ontario Closed (ch)': {
    tournament: 'Ontario Closed Championship',
    location: 'Toronto',
  },
  'Toronto - Ontario Junior': { tournament: 'Ontario Junior', location: 'Toronto' },
  'Toronto - Ontario Open': { tournament: 'Ontario Open', location: 'Toronto' },
  'Toronto - Open': { tournament: 'Open', location: 'Toronto' },
  'Toronto - Simcoe Open': { tournament: 'Simcoe Open', location: 'Toronto' },
  'Toronto - Thanksgiving Open': { tournament: 'Thanksgiving Open', location: 'Toronto' },
  'Toronto Labour Day op': { tournament: 'Labour Day Open', location: 'Toronto' },
  'Toronto Open': { tournament: 'Open', location: 'Toronto' },
  'Toronto Open U2300': { tournament: 'Open', section: 'U2300', location: 'Toronto' },
  'Toronto open U2300': { tournament: 'Open', section: 'U2300', location: 'Toronto' },
  'Toronto, (Labour Day op)': { tournament: 'Labour Day Open', location: 'Toronto' },
  'Toronto, Canada - Ontario Open': { tournament: 'Ontario Open', location: 'Toronto' },
  'United States': { tournament: 'United States' },
  Vancouver: { tournament: '', location: 'Vancouver' },
  'Vancouver (CAN-ch jr)': {
    tournament: 'Canadian Junior Championship',
    location: 'Vancouver',
  },
  'Vancouver (Club Tournament)': { tournament: 'Club Tournament', location: 'Vancouver' },
  'Vancouver (Keres Memorial)': { tournament: 'Keres Memorial', location: 'Vancouver' },
  'Vancouver, Canada (active)': { tournament: 'Active', location: 'Vancouver' },
  'Victoria, Canada (Labour Day Open)': {
    tournament: 'Labour Day Open',
    location: 'Victoria',
  },
  'Windsor, Canada  (February Open)': {
    tournament: 'February Open',
    location: 'Windsor',
  },
  'Windsor, Canada  simul.)': { tournament: 'Simul', location: 'Windsor' },
  'Winnipeg (Canadian Open)': { tournament: 'Canadian Open', location: 'Winnipeg' },
};
