// Names that appear under several spellings in the archive, keyed by the parsed
// "Last, First" form and mapped to the spelling every game will use
export const PLAYER_MERGES: Record<string, string> = {
  'Ahn, Wyntie': 'Ahn, Wyntie Joonho',
  'Armstrong, D.': 'Armstrong, Don',
  'Baxter, W.': 'Baxter, Ward',
  'Bell, Jeff': 'Bell, Jeffrey',
  'Cejvan, S.': 'Cejvan, Sid',
  'Conrad, R.': 'Conrad, Randy',
  'Damianci, Guiherme': 'Damianci, Gui',
  'DeCastro, D.': 'De Castro, D.',
  'Demmery, S.': 'Demmery, Steve',
  'Dobrishman, La': 'Dobrishman, L.',
  'Ehrman, C.': 'Ehrman, Carl',
  'Emery, Matt': 'Emery, Matthew',
  'Filipovich, D.': 'Filipovich, David',
  'Fragakos, A.': 'Fragakos, Angelo',
  'Frilles, R.': 'Frilles, Ruperto',
  'Greeson, Vincent': 'Greeson, Vince',
  'Harris, M.': 'Harris, Mike',
  'Hesletine Nutch, Ka': 'Heseltine Nutch, Ka',
  'Hesletine Nutch, Ke': 'Heseltine Nutch, Ke',
  'Hush, J.': 'Hush, John',
  'Jackson, D.': 'Jackson, Dave',
  'Jackson, David': 'Jackson, Dave',
  'Jung, H.': 'Jung, Hans',
  'Kaczmarek, B.': 'Kaczmarek, Bob',
  'Kain, A.': 'Kain, Andrew',
  'Kearley, J.': 'Kearley, Jim',
  'Khan, Z.': 'Khan, Zamir',
  'Knezevic, A.': 'Knezevic, Adam',
  'Kononenko, Andrei': 'Kononenko, Andrew',
  'Kubik, R.': 'Kubik, Rob',
  'Lau, D.': 'Lau, Daniel',
  'Litchfield, G.': 'Litchfield, Gerry',
  'Lypps, B.': 'Lypps, Bruce',
  'Mak, C.': 'Mak, Calvin',
  'Malik, J.': 'Malik, John',
  'Malik, M.': 'Malik, Miles',
  'Malik, P.': 'Malik, Paul',
  'McGeough, S.': 'McGeough, Shaun',
  'McTavish, D.': 'McTavish, Dave',
  'McTavish, David': 'McTavish, Dave',
  'Mitchell, J.': 'Mitchell, Joe',
  'Moltner, S.': 'Moltner, Stephanie',
  'Moorehouse, D.': 'Moorehouse, Dan',
  'Morabito, M.': 'Morabito, Matt',
  'Nguyen, Ngji': 'Nguyen, Nghi',
  'Ortiz, H.': 'Ortiz, Hugo',
  'Peel, Christopher': 'Peel, Chris',
  'Phares, A.': 'Phares, Adam',
  'Quayle, J.': 'Quayle, Jamie',
  'Rivas, E.': 'Rivas, Edgar',
  'Samano, E.': 'Samano, Elias',
  'Semuranganya, Medi K': 'Semuranganya, Medi Kaliso',
  'Shyr, A.': 'Shyr, Aaron',
  'Shyr, Jn': 'Shyr, Jonathan',
  'Shyr, Js': 'Shyr, Justin',
  'Southam, D.': 'Southam, David',
  'Surlan, D.': 'Surlan, Dan',
  'Thomas, D.': 'Thomas, Dan',
  'Vadhi, Arnav': 'Vadhi, Aarnav',
  'Van De Ven, A.': 'Van de Ven, A.',
  'Van de Ven, Ka': 'Van de Ven, Kaleb',
  'Van de Ven, Ki': 'Van de Ven, Kaleb',
  'van de ven, Kaleb': 'Van de Ven, Kaleb',
  'Van Der Velde, W.': 'Van der Velde, W.',
  'Wilton, T.': 'Wilton, Taylor',
  'Wong, W.': 'Wong, Wylon',
  'Zoccano, J.': 'Zoccano, John',
};

// Games whose White and Black tags were split at the wrong place, keyed by
// "White|Black" as recorded and mapped to the two names as they should read
export const PLAYER_PAIR_FIXES: Record<string, [string, string]> = {
  'Hassan|Gordan, T-StephensonG': ['Hassan Gordon, T.', 'Stephenson, G.'],
  'Heseltine Nutch|Ka-Ferrari, N.': ['Heseltine Nutch, Ka', 'Ferrari, N.'],
  'Pope, J ElieffK|?': ['Pope, J.', 'Elieff, K.'],
  'Teodoro IV, E SouthamT|?': ['Teodoro IV, E.', 'Southam, T.'],
};
