// Generated by backend/scripts/import-tournaments.ts from the records it loads: the
// widest values the tournament tables show, so their columns are sized before anything is fetched
import { TournamentSizing } from '@app/models';

export const TOURNAMENT_SIZING: TournamentSizing = {
  tournaments: [
    {
      name: 'Tandem Simul',
      subtitle: 'Ivanchuk, Serhii 2208 / Ehrman, Carl 2026 / Hampson, Adam 1440',
    },
    {
      name: 'Tandem Simul',
      subtitle: 'Demmery, Steve 2222 / Ruelland, Geoffrey 2161',
    },
    {
      name: 'Tandem Simul',
      subtitle: 'Ruelland, Geoffrey 2162 / Ehrman, Carl 2087',
    },
    {
      name: 'Tandem Simul',
      subtitle: 'Gibson, Kevin 2302 / Ivanchuk, Serhii 2189',
    },
    {
      name: 'COVID-19 Match',
      subtitle: 'Gajiwala, Kiritkumar vs. Sarson, Ryan',
    },
    {
      name: 'Tandem Simul',
      subtitle: 'Gibson, Kevin 2302 / Ehrman, Carl 2075',
    },
    {
      name: 'Blitz',
      subtitle: "Queen's Gambit",
    },
    {
      name: 'Blitz',
      subtitle: 'Dutch Defence',
    },
    {
      name: 'Blitz',
      subtitle: "King's Gambit",
    },
    {
      name: 'Blitz',
      subtitle: 'Sicilian',
    },
    {
      name: 'Blitz',
      subtitle: 'Chess960',
    },
    {
      name: 'London Junior Chess Championship',
      subtitle: '',
    },
    {
      name: 'Vassili Zolotovski Memorial',
      subtitle: '',
    },
    {
      name: 'Summer Solstice Showdown',
      subtitle: '',
    },
    {
      name: 'David Jackson Memorial',
      subtitle: '',
    },
    {
      name: 'Championship Qualifier',
      subtitle: '',
    },
  ],
  timeControls: ['3 hours', 'G90+30', 'G5+3'],
  players: [
    {
      firstName: 'Manju',
      lastName: 'Viralam Lakshminarasimha',
      suffix: '',
    },
    {
      firstName: 'Thamaraiselvan',
      lastName: 'Dhandapani',
      suffix: '',
    },
    {
      firstName: 'Medi Kaliso',
      lastName: 'Semuranganya',
      suffix: '',
    },
    {
      firstName: 'Alistair',
      lastName: 'Dennis-Grantham',
      suffix: '',
    },
    {
      firstName: 'Maheshkumar',
      lastName: 'Jayakrishnan',
      suffix: '',
    },
  ],
  sections: ['Ivanchuk, Serhii 2208', 'Hampson, Adam 1440', 'Ehrman, Carl 2026'],
  resultNotes: [
    'Game incomplete, Winning on board',
    'Draw by mutual agreement',
    'Game incomplete',
  ],
  maxRounds: 9,
  maxPlayers: 82,
  maxSectionPlayers: 65,
  maxRating: 2307,
  maxProvisionalGames: 7,
  maxScore: 11.5,
  hasDateRanges: true,
};
